### ISSUE TITLE
Why does an action created with undefined parameters yields a payload function?

### ISSUE THREAD

**Issue by jcalfee** [mboperator/redux-modules#11]
I have a case where I will create an action without parameters and another case for the same action with parameter.  When called without parameters the `payload` is a function.  This makes is difficult to detect that case.  What is this empty function?  Should payload be undefined or an empty object?
```js 
{
            action: 'SHOW_LOGIN',
            reducer: (state, action) => {
                console.log('action', action)
                console.log('action.payload', action.payload)
                return state
            }
        },
```
```js
console.log(user.actions.showLogin())
```
>action: Object {type: "user/SHOW_LOGIN"}
>action.payload function (a0) {
>	                return fn.apply(this, arguments);
>	            }

**Comment by mboperator** [comment]
Thanks for taking the time to open up an issue for this!

I've never actually called the action creator with an empty payload. I'll make some tests around your case and hopefully we can get this solved today.

**Comment by mboperator** [comment]
Looks like the issue was with my use of `curry`. Fix should be available with the next minor version 😄
