### ISSUE TITLE
Remove redux-actions dependency

### ISSUE THREAD

**Issue by mboperator** [mboperator/redux-modules#25]
### Description
The only method being used in `redux-actions` is `handleActions` which converts the reducer object into a function that receives `state, action`. Additionally, `redux-actions#handleActions` runs at `O(n)`[1]. 

We can remake it with at `O(1)` by using hash lookup. We should replicate this internally to remove the dependency and improve performance.

[1] https://github.com/acdlite/redux-actions/blob/master/src/handleActions.js#L7
  `reduce-reducers` iterates through all the reducer functions and executes them
[2] https://github.com/acdlite/redux-actions/blob/master/src/handleAction.js#L8
  `handleAction` returns state if the type doesn't match

**Comment by wtgtybhertgeghgtwtg** [comment]
Is there a reason why the hash lookup method can't be added to redux-actions?  Would its implementation be specific to redux-modules?

**Comment by mboperator** [comment]
`redux-actions` allows for one action type to map to many reducers. Since `redux-modules` actions map to reducer functions 1:1, we can use an implementation that's more efficient ^^
