### ISSUE TITLE
Add support for multiple modules in the connectModule decorator

### ISSUE THREAD

**Issue by mboperator** [mboperator/redux-modules#26]
### Description
connectModule should accept an array of modules and add their dispatched events to an action hash that contains the module's actions, namespaced. 

### API
```js
const selector = state => {
  return {
    user: { name: state.user.name },
    todos: { collection: state.todos },
  };
};

@connectModule(selector, [ todosModule, userModule ])
class SomeComponent extends React.Component {
  static propTypes = {
    // results from selector, merged with dispatched action props
    user: shape({
      name: string,
      actions: object,  // actions from todos module w/ dispatch mapped
    }),
    todos: shape({
      collection: array,
      actions: object,  //  actions from user module w/ dispatch mapped
    }),
  };
}
```

**Comment by wtgtybhertgeghgtwtg** [comment]
Can this be reverted?  I fail to see any practical application, and it makes `props` complex.  To access the `props` of `todos`, for example, would be
```
const { title, todos: { collection = [], actions: { create, destroy, update } } } = this.props;
```
Instead, it could just be
```
const { title, collection = [], actions: { create, destroy, update } } = this.props;
```
Or, better yet
```
const { title, collection = [], create, destroy, update } = this.props;
```
Additionally, the last approach would allow for the removal of `deep-assign`.

**Comment by mboperator** [comment]
The only things get namespaced now are `actions`:
```js
const selector = state => state.todos
connectModule(selector, todoModule)

// returns 
const props = {
  // selector results
  todos: { actions: { create } }
}
```
The main reason for the namespacing is due to the ability to connect multiple modules.
```js
connectModule(selector, [todoModule, userModule])
const props = {
  todos: { actions: create },
  user: { actions: login }
}
```
Another option that I was exploring was:
```js
const props = {
  // selector results
  actions: { 
    todos: { create }, 
    user: { login } 
  }
}
```

**Comment by wtgtybhertgeghgtwtg** [comment]
I was proposing removing the ability to use multiple modules.  It have many use cases and forces everything in `connectModule` to handle arrays instead of just objects.  If the user needs to, that can use the module composition thing once that's done.

**Comment by mboperator** [comment]
The ability to connect modules is actually quite convenient as it allows handlers to compose module capabilities. For example a login handler might use both a `session` and a `user` module:

````jsx
@connectModule(selector, [user, session])
class LoginHandler extends React.Component {
  static propTypes = {
    user: { current: { }, actions: { login: func } },
    session: { actions: { loadSession: func } },
  }
}
```
In my mind, views and modules were never intended to be 1:1, though looking at `elm` I can see the value.

The ability to connect multiple modules addresses a different use case than the module composition, as module composition is more aimed towards reusing reducers.

**Comment by wtgtybhertgeghgtwtg** [comment]
So then the `user` or `session` modules would be used again somewhere else?

**Comment by mboperator** [comment]
Yes. Potentially on other route handlers that would compose other modules

eg session and todos, user session and todos, etc
