### ISSUE TITLE
Payload Propchecker should accept a Propcheck function instead of an object

### ISSUE THREAD

**Issue by mboperator** [mboperator/redux-modules#44]
### Description
The current only supports `objects` being passed as action payloads:
```js
const transformation = {
  action: 'SET_ACTIVE_ID'
  payloadTypes: { id: number },
  reducer: (state, action) => state.set('activeId', action.payload.id),
}
```

by changing payloadTypes to receive a propType function instead of an object we can do:
```js
const transformation = {
  action: 'SET_ACTIVE_ID'
  payloadTypes: number,
  reducer: (state, action) => state.set('activeId', action.payload),
}
// to replicate above
const transformation = {
  action: 'SET_ACTIVE_ID'
  payloadTypes:shape({ id: number }),
  reducer: (state, action) => state.set('activeId', action.payload),
}
```

**Comment by wtgtybhertgeghgtwtg** [comment]
How is this, or `payloadTypes` in general, going to work if https://github.com/facebook/react/pull/7132 is merged?

**Comment by gaearon** [comment]
You’ll probably want to switch to an open source fork of propTypes (I found a few, e.g. https://github.com/aackerman/PropTypes)

**Comment by mboperator** [comment]
Awesome, thanks for the tip @gaearon 😄 
I was actually thinking of switching to https://www.npmjs.com/package/react-json-schema-proptypes so that I can deep merge them when [combining arrays similarly named of transformations](https://github.com/mboperator/redux-modules/issues/53)
