### ISSUE TITLE
Allow constant actions.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [mboperator/redux-modules#60]
Currently, `transformations` is transformed into an array of action creators.  So, if I have this
```
transformations: [
{
  action: 'INCREMENT_COUNT',
  reducer: state => { ...state, count: ++state.count },
}]
```
I'll get a function called `incrementCount`, which will run through `payloadPropchecker` and `parsePayloadErrors` to dispatch
```
{
  type: 'module/INCREMENT_COUNT',
}
```
This could be avoided by having `createAction` check how many arguments the `reducer` takes and returning an appropriate function accordingly, but that wouldn't work if the `payload` argument of `reducer` has a default value.

**Comment by mboperator** [comment]
I'm confused as to the intent of this issue. Is the goal here to not run `incrementCount` through the `payloadPropchecker`?

**Comment by wtgtybhertgeghgtwtg** [comment]
That's a part of it.  It's probably minor, but
```
args => {
  const action = actionCreatorWithMiddleware(args);
  dispatch(action);
};
```
is less ideal than
```
() => {
  dispatch(action);
};
```

**Comment by mboperator** [comment]
Does closing #61 alleviate this issue a bit? I think the performance implications are probably pretty negligible. 

The only middleware that's included by default in production would be the one that checks if `payload` is an error, and sets the `error` boolean as-per the `flux-standard-action` standard

**Comment by wtgtybhertgeghgtwtg** [comment]
It is probably negligible.
