### ISSUE TITLE
Prepublish ES6

### ISSUE THREAD

**Issue by zachverb** [mboperator/redux-modules#7]
I don't think that you should commit your transpiled code to github, and I don't think you should have people install your module with the non-transpiled code still in the repo if they will never be using it.

People importing your module should already have it in a small consumable format (ie. the ES5 code.)

The most popular way to do this is through [npm pre-publish scripts](http://mammal.io/articles/using-es6-today/)

**Comment by mboperator** [comment]
Thanks for the tip @zachverb ^^
