### ISSUE TITLE
Allow action types to be defined using camelCase

### ISSUE THREAD

**Issue by mboperator** [mboperator/redux-modules#71]
### Description
Currently types are defined with all caps constants, eg:
```js
{
  type: 'ADD_FILTER',
  reducer: state => state
}
// or
{
  ADD_FILTER: state => state
}
```
The library should support camelCased action types:
```js
{
  type: 'addFilter'
}
// or
{
  addFilter: state => state
}
```

Action types should be automatically constantized during the `createModule` call so that the result action type looks like: `modulePrefix/ADD_FILTER` regardless of how `type` is defined.

**Comment by wtgtybhertgeghgtwtg** [comment]
Why?

**Comment by wtgtybhertgeghgtwtg** [comment]
It adds confusion and needless complexity to support both.  Instead of
```
TYPE_NAME => ({ TYPE_NAME, typeName: toCamelCase(TYPE_NAME) })
```
or
```
typeName => ({ TYPE_NAME: toUpper(typeName), typeName })
```
it'd either have to check which one the input is
```
// Produces unexpected results on inputs that are in neither format like "type_name".
input => {
  const isCamelCase = nameIsCamelCase(input);
  return {
    TYPE_NAME: (isCamelCase ? toUpper(input) : input),
    typeName: (isCamelCase ? input : toCamelCase(input)) };
}
```
 or convert both of them
```
// Neither the type nor the function name will be input for inputs like "type_name".
input => ({
  TYPE_NAME: toUpper(input),
  typeName: toCamelCase(input),
})
```

**Comment by mboperator** [comment]
That's true. I've been using `camelCase` type constants lately and I don't even notice the fact that they're not constantized.

Closing this issue.

**Comment by wtgtybhertgeghgtwtg** [comment]
It's not that I disagree with the proposal, it's just that it would be impractical to support both ways.  Deriving the function name from `type` instead of `type` from the function name might be a better idea, anyway.
```
transformations: {
  // Invoked by doThing(), type is DO_THING
  DO_THING: state => state,
}
```
is a little more intuitive when accessing `module.actions` than
```
transformations: {
  // Invoked by doThing(), type is DO_THING
  doThing: state => state,
}
```
You could even have it work as just a default, so that `type` can be explicitly set.
```
transformations: {
  // Invoked by doThing(), type is DO_THING
  doThing: state => state,
  // Invoked by doThing(), type is DO_OTHER_THING_BUT_CALL_IT_SOMETHING_ELSE
  doOtherThing: {
    type: 'DO_OTHER_THING_BUT_CALL_IT_SOMETHING_ELSE',
    reducer: state => state,
  }
}
```

**Comment by mboperator** [comment]
I agree with that. It is much more intuitive to reference the transformation name when calling `module.actions`. Much less magic with this approach, I like it.
