### ISSUE TITLE
Add module wide action middleware

### ISSUE THREAD

**Issue by mboperator** [mboperator/redux-modules#81]
## Description
Per action creator middleware can be repetitive for doing module wide middleware. This would be a convenient shortcut for applying the same middleware to every action creator.

## Proposal
```js
let count = 0;

const countActions = action => {
  count++;
  return {
    ... action,
    meta: { count },
  }
};

const log = action => {
  console.log(action);
  return action;
};

export default createModule({
  name: 'counter',
  initialState: 0,
  middleware: [ countActions, log ],
  transformations: [ ... ],
});
```

**Comment by Nubuck** [comment]
This is awesome. I just wanted to say how much I love redux-modules. This lib has become the heart of my stack and can't live without it. Great work guys, thanks again for all the amazing work.

**Comment by mboperator** [comment]
Thank you for the kind words @Nubuck , it means a lot 😸 Knowing that this is delivering real value to other developers is what keeps the contributions going!

Please tell your friends and if you have time feel free to open issues/PRs for absolutely anything. Also I'm still super curious as to how your stack looks like + how you're using this library. If you ever find some time I'd love to see a gist

**Comment by Nubuck** [comment]
Awesome, I mean it. All my colleagues and friends are using redux-modules. I'll put a gist up today to demonstrate how I'm using them. I've been using them with redux-logic which works amazing, but I'll probably start using redux-loop with the new composes features you guys added :)
