### ISSUE TITLE
Create a decorator that uses `redux-modules` to manage local component state

### ISSUE THREAD

**Issue by mboperator** [mboperator/redux-modules#89]
## Description
Currently `connectModule` connects itself to `redux` via registering its reducer with `ModuleProvider`. It would be cool to have a decorator that instead uses the `module` to manage `React component state`. That way `redux-modules` can be agnostic to the medium that is holding the UI state.

## Example API
```js
@localModule(todoModule)
export default class TodoList extends React.Component {
  static propTypes = {
    collection: array,
    actions: shape({
      create: func,
      destroy: func,
    })
  }
}
```

**Comment by wtgtybhertgeghgtwtg** [comment]
Why would you want that?

**Comment by mboperator** [comment]
Two reasons:
- I like defining state transforms with the `redux-modules` format. I've created some fairly complex UI controls. Most of the state logic is abstracted into a decorator component class, but I think it'd be cleaner to define this in the module format
- It allows us to start components out using internal component state and then moving to storing state in `redux` later if necessary

**Comment by wtgtybhertgeghgtwtg** [comment]
I would say that it is out of the scope of the project.  You would think that `redux-modules` would necessitate `redux`.

**Comment by mboperator** [comment]
I agree with that. I can make this feature in a small, separate repository.
